// Generated by Wrangler on Fri Apr 19 2024 22:55:41 GMT-0400 (Eastern Daylight Saving Time)
// by running `wrangler types --env-interface CloudflareEnv env.d.ts`

interface CloudflareEnv {
	DB: D1Database;
}
